In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df = sns.load_dataset('iris')

In [5]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
from sklearn.preprocessing import LabelEncoder
encoder =LabelEncoder()

In [7]:
df['species'] = encoder.fit_transform(df['species'])

In [8]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [9]:
df.species.unique()

array([0, 1, 2])

In [10]:
df.species.value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2, random_state=1)
#X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=1)

In [18]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [20]:
lor = LogisticRegression()
dtree = DecisionTreeClassifier()

In [25]:
lor.fit(X_train, y_train)
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [26]:
y_train.shape, y_test.shape

((120,), (30,))

In [24]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [27]:
y_pred_lor = lor.predict(X_test)
y_pred_tree = dtree.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [31]:
print('Accuracy score of logistic: ', accuracy_score(y_test,y_pred_lor))
print('Accuracy score of Dicision: ', accuracy_score(y_test,y_pred_tree))

Accuracy score of logistic:  0.9666666666666667
Accuracy score of Dicision:  0.9666666666666667


In [34]:
print('C_matrix of logistic: \n', confusion_matrix(y_test,y_pred_lor))
print('C_matrix score of Dicision: \n', confusion_matrix(y_test,y_pred_tree))

C_matrix of logistic: 
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
C_matrix score of Dicision: 
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [35]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred_lor),columns=list(range(0,3)))

Logistic Regression Confusion Matrix



0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [37]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred_tree),columns=list(range(0,3)))

Decision Tree Confusion Matrix



0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [40]:
from sklearn.metrics import classification_report

In [ ]:
classification_report  =clas