In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('heart.csv')

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,-1], test_size=0.2, random_state=2)

In [23]:
X_train.shape, X_test.shape

((242, 13), (61, 13))

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [25]:
lor = LogisticRegression()
disT = DecisionTreeClassifier()

In [26]:
lor.fit(X_train,y_train)
disT.fit(X_train,y_train)

C:\Users\Mayur\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [27]:
lor.fit(X_train,y_train)

C:\Users\Mayur\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
y_pred_lor=lor.predict(X_test)
y_pred_disT=disT.predict(X_test)

In [29]:
y_pred_disT

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1])

In [30]:
y_pred_disT

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1])

In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('Accuarcy of logisticregrassion: ', accuracy_score(y_test, y_pred_lor))
print('Accuracy of DecisionTree: ', accuracy_score(y_test, y_pred_disT))

Accuarcy of logisticregrassion:  0.9016393442622951
Accuracy of DecisionTree:  0.819672131147541


In [37]:
confusion_matrix(y_test,y_pred_lor)

array([[26,  6],
       [ 0, 29]])

In [38]:
confusion_matrix(y_test, y_pred_disT)

array([[24,  8],
       [ 3, 26]])

In [39]:
pd.DataFrame(confusion_matrix(y_test,y_pred_lor), columns=list(range(0,2)))

0   1
0  26   6
1   0  29

In [40]:
pd.DataFrame(confusion_matrix(y_test, y_pred_disT), columns=list(range(0,2)))

0   1
0  24   8
1   3  26

In [41]:
result = pd.DataFrame()

In [44]:
result['Actual Outpu']=y_test
result['Logistic Prediction']=y_pred_lor
result['Decision Tree']=y_pred_disT

In [46]:
result.sample(10)

Actual Outpu  Logistic Prediction  Decision Tree
29              1                    1              1
267             0                    0              1
175             0                    0              0
288             0                    0              0
232             0                    0              0
296             0                    1              0
157             1                    1              1
188             0                    1              1
66              1                    1              0
89              1                    1              1

In [47]:
from sklearn.metrics import recall_score, precision_score, f1_score

In [53]:
print('For Logistic Regression')
print('-'*50)
cmat = pd.DataFrame(confusion_matrix(y_test,y_pred_lor), columns=list(range(0,2)))
display(cmat)
print('-'*50)
print('Precision: ', precision_score(y_test,y_pred_lor))
print('Recall: ', recall_score(y_test,y_pred_lor))
print('F1 Score: ', f1_score(y_test,y_pred_lor))

For Logistic Regression
--------------------------------------------------


0   1
0  26   6
1   0  29

--------------------------------------------------
Precision:  0.8285714285714286
Recall:  1.0
F1 Score:  0.90625


In [54]:
print('For DecisionTree')
print('-'*50)
cmat = pd.DataFrame(confusion_matrix(y_test,y_pred_disT), columns=list(range(0,2)))
display(cmat)
print('-'*50)
print('Precision: ', precision_score(y_test,y_pred_disT))
print('Recall: ', recall_score(y_test,y_pred_disT))
print('F1 Score: ', f1_score(y_test,y_pred_disT))

For DecisionTree
--------------------------------------------------


0   1
0  24   8
1   3  26

--------------------------------------------------
Precision:  0.7647058823529411
Recall:  0.896551724137931
F1 Score:  0.8253968253968254


In [55]:
# by default the value we get is for class 1  ti check for the both class we use below code

In [56]:
precision_score(y_test,y_pred_lor, average=None)

array([1.        , 0.82857143])

In [57]:
precision_score(y_test,y_pred_disT, average=None)

array([0.88888889, 0.76470588])

In [58]:
recall_score(y_test,y_pred_disT, average=None)

array([0.75      , 0.89655172])