# creating numpy

In [3]:
import numpy as np

In [3]:
# array
a = np.array([0,9,8,7,6,5])

In [4]:
a

array([0, 9, 8, 7, 6, 5])

In [5]:
a=np.array((1,2,3,4))

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a = np.array({1,2,3,4,5}) # will create list having set as an element of type object

In [8]:
a

array({1, 2, 3, 4, 5}, dtype=object)

In [9]:
a = np.array({'mayur':"Lalit"})

In [10]:
a

array({'mayur': 'Lalit'}, dtype=object)

In [11]:
# arange()
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# resahpe()
# this function is used to change the dimention of the array 
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [3]:
# ones()
# this method gives matrix (2D) array of 1 
o = np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
# Zeros
# this method gives 2D array/ matrix of Zeros

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# randome
# this function gives the matrix of ramdom elements range from 0 to 1

np.random.random((3,4))

array([[0.01416029, 0.9589404 , 0.80469751, 0.64681636],
       [0.73190386, 0.77261975, 0.0263169 , 0.70828542],
       [0.69935484, 0.56724166, 0.56790973, 0.16708272]])

In [27]:
# Linspace()
# this function gives the array of linerly spaced elements meance the having the same differnce in all elements

np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [33]:
# identity()
# this function gives the identity matrix 

np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Array Attributes

In [4]:
# ndim
# this attribute gives the dimention of an array

a =np.array([1,2,3,4,5,6], dtype=float)
a2=np.arange(1,13).reshape(6,2)
a3=np.arange(1,13).reshape(2,3,2)

In [5]:
print(a2.ndim)
print(a3.ndim)

2
3


In [45]:
# shape
# this attrib=te gives the dimention of the matix
a.shape #gives the row and column of the arraya

(6,)

In [46]:
a2.shape

(6, 2)

In [47]:
a3.shape

(2, 3, 2)

In [48]:
# size 
# this attribute give the total number of elements in the array
a.size

6

In [49]:
a2.size

12

In [50]:
a3.size

12

In [55]:
# itemsize
# this give the size of the meomory occupied by the eavh item of the array

print(a.itemsize)

8


In [56]:
a2.itemsize

8

In [57]:
a.dtype

dtype('float64')

In [63]:
# astype
# this function is used to change the data type of the col for eg if we have age column having  size of 8 but normaly age is in between 1 to 120 
# it can fit in 4byte as well. so in large data set if we use this function hepls in reducing data size

s = a.astype(np.int32)
s

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [64]:
s.dtype

dtype('int32')

In [65]:
s.itemsize

4

# Arithmatic Operations

In [3]:
import numpy as np
a1 = np.array([1,2,3,4])
a4 = np.array([5,6,7,8])
a2 = np.arange(1,13).reshape(3,4)
a3 = np.ones((3,3), dtype=int) 

In [16]:
print(a1,'\n',a2)
a1 + a2  # vector opeation 

[1 2 3 4] 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [17]:
a2 * a2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [18]:
a2/a1

array([[1.        , 1.        , 1.        , 1.        ],
       [5.        , 3.        , 2.33333333, 2.        ],
       [9.        , 5.        , 3.66666667, 3.        ]])

In [19]:
a2-a1

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [20]:
a2-1 # scaler 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Array Function
### min max sum prod 
#### if you want to calculate the row wise, add parameter axis=1 for row by default it is 0

In [5]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
print(np.min(a1))

1


In [8]:
print(np.min(a2, axis=1))

[1 5 9]


In [9]:
print(np.min(a2, axis=0))

[1 2 3 4]


In [26]:
print(np.max(a1))

4


In [11]:
print(np.prod(a2, axis=1))

[   24  1680 11880]


In [30]:
print(np.sum(a3))

12


### mean median std var

In [33]:
print(np.mean(a1))

2.5


In [34]:
print(np.mean(a2))

6.5


In [36]:
print(np.median(a2))

6.5


In [37]:
np.var(a2)  # variance

np.float64(11.916666666666666)

In [38]:
print(np.std(a2))

3.452052529534663


## Log exp

In [40]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [41]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [42]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [43]:
np.exp(a2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [15]:
ran = np.random.random((3,3))
ran

array([[0.66112735, 0.64394184, 0.09672201],
       [0.43409287, 0.20141561, 0.93539223],
       [0.88457781, 0.2206706 , 0.25117556]])

## floor round ceil

In [17]:
# floor function roung off the floting point value and give the value before the decimal point only
np.floor(ran)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# ceil() functiont gives next value leavig the decimal points 
print(np.ceil(5.2))
np.ceil(ran)

6.0


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# the round() give the next value if it is more than .5 and give before value if less than .5 
print(np.round(5.7))
np.round(ran)

6.0


array([[1., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [55]:
np.dot(a3, ran) # dot product is possible if the rows and col are of same size of both matrix

array([[1.56990791, 1.53278782, 1.15028206],
       [1.56990791, 1.53278782, 1.15028206],
       [1.56990791, 1.53278782, 1.15028206]])

# Indexing and  Slicing 

In [21]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [23]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
print(a1[-1]) # works same as like list in python 

9


In [30]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
print(a2[2][-1]) # works same as the list in python 
print(a2[2,-1]) # in single list 

11
11


In [39]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
print(a3[1,0,0])

4


In [40]:
print(a3[-1,-1,-1])

7


In [42]:
# Slicing 
print(a1[0:3])

[0 1 2]


In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
print(a2[:,::2]) # here [start:end:steps, start:end:steps] the first parameter is for row and the second is for cols

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [53]:
print(a2[::2, 1::2])

[[ 1  3]
 [ 9 11]]


In [58]:
print(a2[:2,1:])

[[1 2 3]
 [5 6 7]]


In [55]:
print(a2[1:2,0::3])

[[4 7]]


In [52]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
print(a4[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [64]:
a4[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
a4[0][1]
print(a4[0,1])

[3 4 5]


In [76]:
print(a4[1][::, 1:2])
a4[1,:,1]  # [element ::, rows::, cols::]

[[10]
 [13]
 [16]]


array([10, 13, 16])

In [77]:
a4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [81]:
a4[::2,0,::2]  #[select the items in 3d list, number of rows which are required, number of column required]
               #[select all having step count 2, number of row which is 0 , column all having step 2]

array([[ 0,  2],
       [18, 20]])

# Iteration
## nditer()
#### this function iterate through all the items in the array

In [92]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [87]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [88]:
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [86]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [91]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


# Reshaping
### this include reshape(), transpose() and ravel() function

In [93]:
# transpose()
# this function os used to transpose the matrix i.e row to col and col to rows
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
a2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
# ravel
# this fuction retun the array list of all elements in all types of array

a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [97]:
a4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking
#### used to join the two or more than to arrays in two different ways i.e vertical and horizontal

In [102]:
s1 = np.arange(12).reshape(3,4)
s2 = np.arange(12,24).reshape(3,4)
s1,s2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [103]:
# this function join the more than two arrays horizontally
np.hstack((s1,s2)) 

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [108]:
# this function joins the array one above another 
s3 = np.vstack([s1,s2])
s3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
### this function is the opposite of stacking i.e it split the arrayinto equal parts 

In [109]:
np.hsplit(s3,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [112]:
np.vsplit(s3, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]