# np.sort

In [3]:
import numpy as np
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [4]:
a,b

(array([ 4, 41,  2, 79, 27,  4, 88,  4, 28, 56,  9, 66, 98, 97, 54],
       dtype=int32),
 array([[78, 99, 76, 15],
        [64, 27, 95,  5],
        [49,  6,  5, 79],
        [31, 63, 47, 80],
        [59, 87, 19,  3],
        [96, 40, 92, 30]], dtype=int32))

In [5]:
np.sort(a)

array([ 2,  4,  4,  4,  9, 27, 28, 41, 54, 56, 66, 79, 88, 97, 98],
      dtype=int32)

In [8]:
np.sort(b, axis=0) # 0 colwise 1 row wise

array([[31,  6,  5,  3],
       [49, 27, 19,  5],
       [59, 40, 47, 15],
       [64, 63, 76, 30],
       [78, 87, 92, 79],
       [96, 99, 95, 80]], dtype=int32)

# np.append()
#### this function appends the new element indexwise to the array

In [10]:
np.append(a,100)

array([  4,  41,   2,  79,  27,   4,  88,   4,  28,  56,   9,  66,  98,
        97,  54, 100])

In [11]:
np.append(a[1],200)

array([ 41, 200])

In [12]:
a

array([ 4, 41,  2, 79, 27,  4, 88,  4, 28, 56,  9, 66, 98, 97, 54],
      dtype=int32)

In [19]:
np.append(b,np.ones((b.shape[0],1)), axis=1)

array([[78., 99., 76., 15.,  1.],
       [64., 27., 95.,  5.,  1.],
       [49.,  6.,  5., 79.,  1.],
       [31., 63., 47., 80.,  1.],
       [59., 87., 19.,  3.,  1.],
       [96., 40., 92., 30.,  1.]])

In [27]:
np.append(b, np.random.random((b.shape[0],1)),axis=1)
#np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[78.        , 99.        , 76.        , 15.        ,  0.83631317],
       [64.        , 27.        , 95.        ,  5.        ,  0.37061805],
       [49.        ,  6.        ,  5.        , 79.        ,  0.51315756],
       [31.        , 63.        , 47.        , 80.        ,  0.80367055],
       [59.        , 87.        , 19.        ,  3.        ,  0.16622143],
       [96.        , 40.        , 92.        , 30.        ,  0.57423753]])

# np.concatenate()
#### this method used to concatinate two or more than two arrays

In [3]:
import numpy as np
x = np.arange(1,7).reshape(3,2)
y = np.arange(7,13).reshape(3,2)

In [7]:
np.concatenate((x,y), axis = 1)

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

# np.unique()
#### this method gives unique elements from the array 

In [8]:
e = np.array([1,2,3,3,4,4,5,5,6,6,7,7,8])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8])

# np.expand_dims()
#### this method gives the expanded dimention of the array if array is 1d will give 2d as below this is useful in ML and DL algorithim to expand data DIM

In [14]:
np.shape(e) # this is 1D array 

(13,)

In [18]:
np.expand_dims(e,axis=0)

array([[1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8]])

In [24]:
np.shape(np.expand_dims(e,axis=0)) # will add other dimention t the array 


(1, 13)

In [25]:
np.shape(np.expand_dims(e,axis=1)) #

(13, 1)

# np.where()
#### this method return the index of the element if condition is satisfied

In [27]:
arr = np.random.randint(1,20,10)
arr

array([18,  6, 13, 17, 11, 19, 16,  6,  8, 11], dtype=int32)

In [30]:
np.where(arr>15)

(array([0, 3, 5, 6]),)

In [31]:
arr[np.where(arr>15)]

array([18, 17, 19, 16], dtype=int32)

# np.argmax()
#### this method returns index of the maximum arguments axis wise

In [34]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[68, 39, 78, 26],
       [ 7, 40, 52, 49],
       [42, 23, 83, 93],
       [97, 11, 60, 73],
       [62,  4, 79, 81],
       [52, 97,  6, 59]], dtype=int32)

In [40]:
np.argmax(b, axis=1) # gives the row index of the max argument

array([2, 2, 3, 0, 3, 1])

# argmin()

In [42]:
np.argmin(b) # in this type method will condnside 1d array and gibe the index of the element as 4 is the smallest elements

np.int64(17)

In [44]:
np.argmin(b, axis=0)

array([1, 4, 5, 0])

# cumsum() / cumprod()
#### this method givs the cimulative sum of array as by adding the previous sum to the currect item and product give the product of all by multiplying previous product

In [47]:
a = np.random.randint(1,100,15)
a

array([31, 89, 80, 83, 32, 20, 15, 75, 86, 72, 80, 54, 39, 94, 36],
      dtype=int32)

In [48]:
np.cumsum(a)

array([ 31, 120, 200, 283, 315, 335, 350, 425, 511, 583, 663, 717, 756,
       850, 886])

In [49]:
np.cumprod(a)

array([                  31,                 2759,               220720,
                   18319760,            586232320,          11724646400,
               175869696000,       13190227200000,     1134359539200000,
          81673886822400000,  6533910945792000000,  2343053672286519296,
        -854627149373505536, -6547975746271313920,  4080546092456869888])

# np.percentile()
#### this method used to calculate the nth percentile of the element from the array axis wise 

In [53]:
a
print(np.percentile(a,80)) # meance 83% are having less percentile than the current item in the array

83.60000000000001


# np.histogram()
#### this function gives the frequency of data distribution in the graphical form, using bin size 

In [55]:
np.histogram(a,[0,10,20,30,40,50,60,70,80,90,100])    # size of bins to find data disrtibution

(array([0, 1, 1, 4, 0, 1, 0, 2, 5, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# corrcoef()
#### this method return the correlation between the quantites 


In [56]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [57]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin() 
#### method i used to check the iteam of one arrya present in the other array 

In [64]:
print(a)
items = [10,22,32,46,86,36]

[31 89 80 83 32 20 15 75 86 72 80 54 39 94 36]


In [65]:
np.isin(a,items)

array([False, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False,  True])

# np.flip() 
#### this method reverse the array element you can specify the axis also to fip axis wise

In [68]:
a,b

(array([31, 89, 80, 83, 32, 20, 15, 75, 86, 72, 80, 54, 39, 94, 36],
       dtype=int32),
 array([[68, 39, 78, 26],
        [ 7, 40, 52, 49],
        [42, 23, 83, 93],
        [97, 11, 60, 73],
        [62,  4, 79, 81],
        [52, 97,  6, 59]], dtype=int32))

In [69]:
np.flip(a) # reverse the array

array([36, 94, 39, 54, 80, 72, 86, 75, 15, 20, 32, 83, 80, 89, 31],
      dtype=int32)

In [70]:
np.flip(b) # reverse by both row and col wise

array([[59,  6, 97, 52],
       [81, 79,  4, 62],
       [73, 60, 11, 97],
       [93, 83, 23, 42],
       [49, 52, 40,  7],
       [26, 78, 39, 68]], dtype=int32)

In [71]:
np.flip(b, axis=1) # row_wise

array([[26, 78, 39, 68],
       [49, 52, 40,  7],
       [93, 83, 23, 42],
       [73, 60, 11, 97],
       [81, 79,  4, 62],
       [59,  6, 97, 52]], dtype=int32)

# np.put
#### this method replace the elements in the old array using index position

In [72]:
a

array([31, 89, 80, 83, 32, 20, 15, 75, 86, 72, 80, 54, 39, 94, 36],
      dtype=int32)

In [73]:
np.put(a, [0,1],[100,200]) # this method makes the actual changes in the array (array_name, list of index, values by which replace)

In [74]:
a

array([100, 200,  80,  83,  32,  20,  15,  75,  86,  72,  80,  54,  39,
        94,  36], dtype=int32)

# np.delete
#### this method delete the array elements by specifying the index of elements. we can pass the list of indices 

In [75]:
np.delete(a,[0,1,2]) # this is temp operation and not change actual array

array([83, 32, 20, 15, 75, 86, 72, 80, 54, 39, 94, 36], dtype=int32)

In [76]:
a

array([100, 200,  80,  83,  32,  20,  15,  75,  86,  72,  80,  54,  39,
        94,  36], dtype=int32)

# Set function

In [2]:
import numpy as np
p=np.array([1,2,3,4,5])
q=np.array([4,5,6,7,8])

In [3]:
np.union1d(p,q)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.intersect1d(p,q)

array([4, 5])

In [5]:
np.setdiff1d(q,p)

array([6, 7, 8])

In [6]:
np.setxor1d(p,q) # the uncommon elements xor 

array([1, 2, 3, 6, 7, 8])

In [7]:
np.in1d(p,q) # same as is in method who check if the 

C:\Users\Mayur\AppData\Local\Temp\ipykernel_15032\2907374133.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(p,q)


array([False, False, False,  True,  True])